# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BootstrapIterKNMScores <- function(iterProbMat) {
    .Call('svmSCORES_BootstrapIterKNMScores', PACKAGE = 'svmSCORES', iterProbMat)
}

empiricalPvalues <- function(nullvec, vec) {
    .Call('svmSCORES_empiricalPvalues', PACKAGE = 'svmSCORES', nullvec, vec)
}

compPvals2 <- function(nullvec, vec) {
    .Call('svmSCORES_compPvals2', PACKAGE = 'svmSCORES', nullvec, vec)
}

compPvals3 <- function(nullvec, vec) {
    .Call('svmSCORES_compPvals3', PACKAGE = 'svmSCORES', nullvec, vec)
}

